source 'https://supermarket.chef.io'

metadata

cookbook 'application_ruby'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'chef_rvm'
cookbook 'chefdk'
cookbook 'chef_nginx'
cookbook 'curl'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'locale'
cookbook 'nodejs'
cookbook 'openssl'
cookbook 'postgresql'
cookbook 'powershell'
cookbook 'ruby_build'
cookbook 'runit'
cookbook 'ssh_known_hosts'
cookbook 'user'
cookbook 'vim'
cookbook 'ruby_rbenv'
cookbook 'poise-ruby'

cookbook 'ohai' # needed for setting up the ohai plugin
# cookbook' compat_resource' # needed for Chef 12.1 - 12.13
cookbook 'yum-epel' # needed for setting up the EPEL repository on RHEL platforms
