---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  markdownlint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/HandleExceptions:
        enabled: false
ratings:
  paths:
  - Gemfile.lock
  - app/**
  - lib/**
  - "**.erb"
  - "**.rb"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.md"
  - "**.module"
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
  - config/
  - db/
