language: ruby
rvm: 2.3.3
env: DB=postgres
script: bundle exec rspec
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: qw0i5Kc7iE5JFQKPaA3QIXhqKEhM3Sds2P2feVVqIp+60Oqt64l725J5YD4U9kWCSPpuM9ofhRsSofma/kt4n6fYHDL/cuE4DPZD4f1JGr8c9Vzq1cHRzl05hX3SvQv9fAlDb7uL8QMo1FOdEM6FM+56wKimAU8A9RFkRlsf7bkmv/053F1YDlzLtT7ANA1tVd9Lc5hMKEhctAGFVrAsM+cjR/w/FXa+vZb6GutFQKcHKVGPHNBiDgYzwB6t9Fje0MNKLEJmicCDapY7VkWud8pBMkZatc8Dx2/su73j0rF9reHFOHbiUBfLo6annWDAXje7yuesFi2qbcNc3VZAq2msp06jFyc37n7GJy/W21YXM4WQPA0AcvOD7SBXb8bZvmrt3qWXmoqmFvLHsdgrSs2PKRhqrefwKWP9HbpsIoPMGKMiWGWCnjAjZFCMSlb2ZQta9drchr0EoMRL1UbSy6UbZoW1nHi+KGwTQPPC3uXopAnnQ5q6GqjGAsstH3XEHdfvGUH1V1qSX/g4p2UydPwy7U0Gz4Y4q1XTQgfw9gJiGUUuv1NswenpWKiE5+fmPr9TLpLYPGkOUfBz76RAVJhS4XdaLoeHHMccKHp/UxPayuYsiXzJjkVh3jQoAgPJmShNb1THGKIgRUZ7nRmZk49DXU/cXTKi8dzAx/X5HI4=
after_success: CODECLIMATE_REPO_TOKEN=4b32831b3a5bbfe1793fb8c7bdc481d23590f390e60ed3834d84348f0c34f890 bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
install: bundle install --jobs=3 --retry=3
