# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49caf107c3856881b9d309a310fd8c47d9ce9cb55fde3750cfeeafa5cb93139ef99a9808adfffd2e03853cd6dc6dd766986252b808484b03f588a046740e34d4
  flickr_api_key: <%= ENV['FLICKR_KEY'] %>
  flickr_secret: <%= ENV['FLICKR_SECRET'] %>

test:
  secret_key_base: e9dc2e3878962e5f950265c8e23f485b3d1a32f6900c0448ad580d88df1eff719675b17a3dfde294fde829e2841d1dbe9d77540af029bfde73c3cc1f03a2fd49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
  flickr_api_key: <%= ENV['FLICKR_KEY'] %>
  flickr_secret: <%= ENV['FLICKR_SECRET'] %>
